### ISSUE TITLE
[Docs] Add comments and documentation

### ISSUE THREAD

**Issue by tiagojpdias** [vostpt/bot#13]

**Comment by miguelcarreiro** [comment]
Commit (806fc2278701cf20133bb6a84e464e443daead91) and [Pull Request](https://github.com/vostpt/bot/pull/16) done

**Comment by miguelcarreiro** [comment]
Update - new commit (4eae787953feb2877b1cc29237acdf8e32b2f99e)

**Comment by miguelcarreiro** [comment]
'/services' code commenting completed

**Comment by miguelcarreiro** [comment]
@tiagojpdias Although I've already completed code commenting from '/services' folder, there are still code to comment in other folders, as you can see below:
- [x] '/services' - [PR #41](https://github.com/vostpt/bot/pull/41);
- [x] '/commands' - [PR #46](https://github.com/vostpt/bot/pull/46);
- [x] '/events' - [PR #68](https://github.com/vostpt/bot/pull/68);
- [x] '/triggers' - [PR #68](https://github.com/vostpt/bot/pull/68);
- [x] '/helpers' - [PR #68](https://github.com/vostpt/bot/pull/135);
- [x] '/jobs';
