### ISSUE TITLE
[FEAT] [High Priority] Meteo Alarm Weather Warnings for VOST Europe

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/bot#189]
<h1>CONTEXT</h1>

**VOST Portugal** is a part of **VOST EUROPE**, that congregates all the European VOST Teams. The [VOST Europe](https://twitter.com/VOSTeurope) account on Twitter is, at the moment, being update due to the dedication, and commitment,  of [Iraxte](https://twitter.com/iratxegs) with no technological support whatsoever. Weather warnings, of any kind, throughout Europe, are an important part of the content being amplified by the account, and it has vital importance within the European space. 

<h1>FEATURE REQUEST</h1>

Using the data, publicly available @ [**Meteo Alarm**](http://meteoalarm.eu/?lang=en_UK), transpose the weather warnings implemented for the **[VOSTPT](https://twitter.com/vostpt)** twitter account (Implemented in  https://github.com/vostpt/bot/issues/24) so that the VOST Europe account starts sending timely weather warnings. 

<h1>DEVELOPMENT NOTES</h1>
App and Secret Keys for the account will be provided by @JorgeMiguelGomes on request.

**Comment by miguelantoniosantos** [comment]
The way I found for parsing is:
 
We get all the countries with warnings with:

```javascript
let warnings = document.querySelectorAll('.warn.awt');

let country_url = warning[0].parentElement.parentElement.href;
```

Go through each one that is unique.

Then we have two options, processing the tooltip or opening the region warning and parsing the region page.
I suggest going to the region page as it seems more consistant.

```javascript
let warnings = document.querySelectorAll('.warn2.awt2');

let text = warnings[0].parentElement.parentElement.getAttribute('onclick');

let regex = /transfer_to_area\('([^']+)'\)/m;

let region_url= text.match(regex)[1]);
```

And in the region page we parse the region name warnings and all the data needed.

@miguelcarreiro seems good?

**Comment by miguelcarreiro** [comment]
> The way I found for parsing is:
> 
> We get all the countries with warnings with:
> 
> ```js
> let warnings = document.querySelectorAll('.warn.awt');
> 
> let country_url = warning[0].parentElement.parentElement.href;
> ```
> 
> Go through each one that is unique.
> 
> Then we have two options, processing the tooltip or opening the region warning and parsing the region page.
> I suggest going to the region page as it seems more consistant.
> 
> ```js
> let warnings = document.querySelectorAll('.warn2.awt2');
> 
> let text = warnings[0].parentElement.parentElement.getAttribute('onclick');
> 
> let regex = /transfer_to_area\('([^']+)'\)/m;
> 
> let region_url= text.match(regex)[1]);
> ```
> 
> And in the region page we parse the region name warnings and all the data needed.
> 
> @miguelcarreiro seems good?

@miguelantoniosantos Looks good, although Meteoalarm also has a RSS feed with the [list of countries](https://www.meteoalarm.eu/documents/rss/europa.rss), and then each country have it's own RSS feed with [all regions](https://www.meteoalarm.eu/documents/rss/ie.rss).
I watched RSS feeds, and it has some problems, for example, the only way to see if a warning was issued is by looking at the image URL, whereas in source code we can check 'warn2' class attribute), so I think that scraping would be a better solution.

**Comment by JorgeMiguelGomes** [comment]
@miguelantoniosantos &  @miguelcarreiro how long will it take to implement this? **Real expectations, please**

**Comment by miguelantoniosantos** [comment]
After a direct chat with @miguelcarreiro, we decided @miguelcarreiro will be making the twitter integration, I (@miguelantoniosantos) will be making the scrapper.

The scrapper will be an module with the following format:

```javascript
class MeteoAlarm {
   async fetch() {
   }
   async fetchSingle(countryShortcode) {
   }
}
module.exports = new MeteoAlarm();
```

They async function fetch will return an object with the _keys_ being a country short code and the value being an _array_.
This _array_ will have multiple (0+) _objects_, representing an alert, with the following format:

```javascript
{
      type: '',
      status: '',
      start: '',
      end: '',
      severity: '',
      region: '',
}
```

I predict having the scrapper done at the end of Friday (02/09/2020 23:59)

**Comment by JorgeMiguelGomes** [comment]
> I predict having the scrapper done at the end of Friday (02/09/2020 23:59)

**Sounds great!**

**Comment by miguelantoniosantos** [comment]
Created a [gist ](https://gist.github.com/miguelantoniosantos/642ff02932b905a061dea85abf3f7aef) with an example output of MeteoAlarm.fetch()

Here is an example use of the scrapper: 

```javascript
const MeteoAlarm = require('./api/MeteoAlarm');


async function get() {
  const portuguese_data = await MeteoAlarm.fetchSingle('PT');
  const all_data = await MeteoAlarm.fetch();
}

get();
```
