### ISSUE TITLE
[FEAT] [COVID19PT] Create command to update, via Discord, the daily numbers 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/bot#190]
<h1>CONTEXT</h1>
Since the beginning of the pandemic, the process to publish the new numbers on Twitter has been evolving. **However this is still a manual task**, that requires human intervention every single day, on demand whenever the report arrives via email. 

Due to the report's format constraints and lack of stability in that format, we will still need human intervention, but we can limit that to a minimum. 

<h1>FEATURE REQUEST</h1>
<h3> High Priority</h3>

- [x] Develop a command where authorized users can tell the bot what the new **numbers** are
- [x] Have the bot update the the daily numbers table 
- [x] Have the bot return to the discord channel the new numbers and percentages (compared to the last day)

<h3>It would be cool priority</h3>

- [ ] Have the bot upload the new report to the respective Google Drive folder
- [ ] Have the bot generate a bit.ly with the shared link using [bit.ly's API](https://dev.bitly.com/)
- [x] Have the bot **tweet** the new numbers and respective link 
- [ ] Have the bot send the notification to the "EstamosOn" app, via [Firebase's API](https://firebase.google.com/docs/reference)
- [x] Have the bot send the information and the original PDF to [VOSTPT's Telegram channel](https://t.me/vostpt)

<h3>DEFINITIONS</h3>

**Numbers** to be included: 

- total cases
- total recovered
- total deaths
- total at hospital 
- total at intensive care

**Comment by JorgeMiguelGomes** [comment]
**High Priority** is closed, correct @miguelcarreiro ?

**Comment by miguelcarreiro** [comment]
> **High Priority** is closed, correct @miguelcarreiro ?

Yes. I also edited your comment to include checkboxes with the implementation status.
Since I'll start working on #189, the "It would be cool priority" features will not be ready in the next few days.

**Comment by miguelcarreiro** [comment]
In the cool priority tasks, Twitter and Telegram were completed.
It wasn't possible to implement bit.ly since their API doesn't allow to create custom links using the free version, and Estamos ON notifications, since the app was discontinued.
Google Drive file upload feature wasn't implemented for now.
