### ISSUE TITLE
[BUG] miscellanous.js - "vostpt" trigger behaviour 

### ISSUE THREAD

**Issue by VOSTPortugal** [vostpt/bot#20]
The bot should not reply to the user but to just send message to the public channel. 
**Example:**
JG: A VOSTPT (...)
VOSTia: Sabias que a VOST Portugal (...)

**Comment by tiagojpdias** [comment]
@VOSTPortugal is this still happening?

**Comment by JorgeMiguelGomes** [comment]
This was scratched. Bot should be able to be mentioned and reply from the random list he has.
