### ISSUE TITLE
[feat] Mirror posting of @Portugal_DRE 

### ISSUE THREAD

**Issue by lisbonjoker** [vostpt/bot#234]
I feel it's a informartive account that would also be a fit to be posted on the fediverse.

**Comment by miguelcarreiro** [comment]
Great idea! I will implement this feature, creating a new [@Portugal_DRE](https://twitter.com/Portugal_DRE) page in Pleroma, where the bot will send new decrees.

**Comment by miguelcarreiro** [comment]
Done ✅
The page is available [here](https://pleroma.pt/@Portugal_DRE). Thanks for the suggestion!
