### ISSUE TITLE
[Bug] Fix hour

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/bot#62]
Bot is returning the real date+hour time plus one hour.

**Comment by tiagojpdias** [comment]
Can you elaborate more on this?

**Comment by gadelhas** [comment]
This was created of me. It's a problem with the way we are retrieving the dates from ProCiv website.
Timezone problems.

**Comment by tiagojpdias** [comment]
Should we point to the new VOST API?
@quetzyg is this issue also occurring in API? Are you manipulating dates in any way?

**Comment by quetzyg** [comment]
The ProCiv dates are stored without any sort of change, timezone and everything.

**Comment by quetzyg** [comment]
The timezone of all ProCiv dates is `+0100`, like in the example:
https://github.com/vostpt/api/blob/master/app/Jobs/Occurrences/OccurrenceFetcher.php#L221

**Comment by tiagojpdias** [comment]
@miguelcarreiro was the PR #102 related to this ticket?

**Comment by gadelhas** [comment]
Yes. Closing this issue.

**Comment by miguelcarreiro** [comment]
As @gadelhas said, #102 was related to this issue, but I didn't remember to close it.
