### ISSUE TITLE
[Feat] Bot should send commands via private message

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/bot#73]
In order to avoid cluttering channels with information, when a user sends the "?commands" command, the bot should:
- reply to the user that the command's list was sent via private message
- send commands' list via private message

**Comment by miguelcarreiro** [comment]
Issue fixed in commit https://github.com/vostpt/bot/commit/57760969c5059aca56d79b67756258d860652a46, and PR https://github.com/vostpt/bot/pull/75
