### ISSUE TITLE
Commands and Structure

### ISSUE THREAD

**Issue by VOSTPortugal** [vostpt/bot#8]
**These commands should be in a separate folder called "**fires**", with a file for each command:**
!all 
!all [human|ground|air] [numero_filtrar] 
!all links 
!all important 
!op id [numero_id] 
!op if [#IFConcelho] 
!op status [Despacho|Curso|Resolução|Conclusão|Vigilância] 
!op distrito [nome_distrito]
!rmc

------
**These commands should be in a separate folder called "**weather**", with a file for each command:**
 !weather 
!weather tomorrow

-----
Interaction with Twitter should be made via a separate file.

**Comment by JorgeMiguelGomes** [comment]
Closing issue as it has been resolved, brilliantly, by @tiagojpdias
