### ISSUE TITLE
[Bug] Bot fetching and tweeting same weather warning several times 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/bot#98]
Bot is posting the same weather warning over and over again to Discord and Twitter.

It **should only do it once**
Exception: If warning is posted between 00h and 5h, it should repeat at 7am.

**Comment by miguelcarreiro** [comment]
This issue is fixed (except the `exception` part), but since #101 will bring a new approach to catch IPMA weather warnings, I will create a new issue for #101, and close this one.

@JorgeMiguelGomes If you consider that the `exception` part is relevant enough to reopen this issue, please do it.
